.TH "FRESHBOOKS\-INVOICE" "" "November 2013" "" ""
.SH "NAME"
\fBfreshbooks-invoice\fR
.QP
.P
A command\-line interface for interacting with Freshbooks Invoices

.
.SH Usage
.P
.RS 2
.EX
\-\-list, \-l   \- Display a full list of invoices

\-\-create, \-c \- Create an invoice from JSON data, either
               read from STDIN or passed to \-\-data as a string

\-\-data JSON \- Invoice data for \-\-create

\-\-help, \-h \- Display this message
.EE
.RE
.P
See http://developers\.freshbooks\.com/docs/invoices/ for more information\.
.SH Examples
.P
.RS 2
.EX
# Displaying the full list of invoices
$ freshbooks projects \-\-list
.EE
.RE